apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: todo-backend
        image: purvjoshi4/projects:todo-app-test-4
        ports:
        - containerPort: 3000
        volumeMounts:
          - name: env-file
            readOnly: true
            mountPath: "/app/secret"
      volumes:
      - name: env-file
        secret:
          secretName: backend-secret